# docker-compose.yml
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ervishal
      POSTGRES_PASSWORD: archiq763
      POSTGRES_DB: archiq
    volumes:
      - postgres_data:/data
    
  redis:
    image: redis:7-alpine
    container_name: archiq-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
