name: Deploy API

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/archiq-api:latest \
            -t ghcr.io/${{ github.repository_owner }}/archiq-api:${{ github.sha }} \
            .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/archiq-api:latest
          docker push ghcr.io/${{ github.repository_owner }}/archiq-api:${{ github.sha }}

      - name: Install Doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy on DO
        run: |
          doctl apps create-deployment 63add680-6615-44d7-b63c-9e7dccb7e08d --force-rebuild